# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 08:44
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.CharField(default=blog.models.next_id, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.FloatField(default=time.time)),
            ],
        ),
    ]
